### ISSUE TITLE
BUG no clique do E-mail

### ISSUE THREAD

**Issue by MisteriumEz** [Diego10Rocha/Diego10Rocha.github.io#1]
Algumas vezes quando se clica no Email, ele dá uma bugadinha e não abre para mandar mensagem.

É raro e só rolou duas vezes aqui, quando rolar de novo boto um print aqui.

**Comment by Diego10Rocha** [comment]
Obrigado, meu bom!
Você tem seu portfólio?

Em sex., 30 de jul. de 2021 16:41, Big Tony ***@***.***>
escreveu:
